ifdef CONFIG_KMSAN

# Too many unused functions in include/linux/kmsan-checks.h
CFLAGS_KMSAN := -fsanitize=kernel-memory -Wno-unused-function -mllvm -msan-handle-asm-conservative=1

ifeq ($(call cc-option, $(CFLAGS_KMSAN) -Werror),)
   ifneq ($(CONFIG_COMPILE_TEST),y)
        $(warning Cannot use CONFIG_KMSAN: \
            -fsanitize=kernel-memory is not supported by compiler)
   endif
endif

endif
